import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/LandingPageComponents/Navbar";
import Footer from "./components/LandingPageComponents/Footer";
import SocialFooter from "./components/LandingPageComponents/SocialFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Navbar */}
        <header>
          <Navbar />
        </header>

        {/* Contenido principal */}
        <main className="flex-grow">{children}</main>

        {/* Footer */}
        <footer>
          <SocialFooter />
          <Footer />
        </footer>
      </body>
    </html>
  );
}
